# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/database/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
filter = { except_tables = ["community_rules", "mint_guilds", "potential_guilds"] }

[migrations_directory]
dir = "migrations"

